<?php
    $countries = [
    "Argentina" => "Argentina"
    ,"Algeria" => "Algeria"
    ,"Afghanistan" => "Afghanistan"
    ,"Angola" => "Angola"
    ,"Armenia" => "Armenia"
    ,"Austria" => "Austria"
    ,"Australia" => "Australia"
    ,"Boukina Faso" => "Boukina Faso"
    ,"Bulgaria" => "Bulgaria"
    ,"Britain" => "Britain"
    ,"Belgium" => "Belgium"
    ,"Bolivia" => "Bolivia"
    ,"Benin" => "Benin"
    ,"Brazil" => "Brazil"
    ,"Belarus" => "Belarus"
    ,"Cameroon" => "Cameroon"
    ,"Czech" => "Czech"
    ,"Chile" => "Chile"
    ,"Chad" => "Chad"
    ,"China" => "China"
    ,"Costa Rica" => "Costa Rica"
    ,"Canada" => "Canada"
    ,"Croatia" => "Croatia"
    ,"Colombia" => "Colombia"
    ,"Congo DR" => "Congo DR"
    ,"Congo" => "Congo"
    ,"Denmark" => "Denmark"
    ,"Argentina" => "Argentina"
    ,"Argentina" => "Argentina"
    ,"Argentina" => "Argentina"
];
?>

